import mongoose from 'mongoose';

const ClientSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  description: { type: String },
  evidence: { type: String },
  amountLost: { type: Number, default: 0 },
  data: {
    verifiedLoss1: { type: Number, default: 0 },
    verifiedLoss2: { type: Number, default: 0 },
    verifiedLoss3: { type: Number, default: 0 },
    verifiedLoss4: { type: Number, default: 0 },
    verifiedLoss5: { type: Number, default: 0 },
    verifiedLoss6: { type: Number, default: 0 },
    verifiedLoss7: { type: Number, default: 0 },
    verifiedLoss8: { type: Number, default: 0 },
    verifiedLoss9: { type: Number, default: 0 },
    verifiedLoss10: { type: Number, default: 0 },
    verifiedLoss11: { type: Number, default: 0 },
    verifiedLoss12: { type: Number, default: 0 },
    verifiedLoss13: { type: Number, default: 0 },
    verifiedLoss14: { type: Number, default: 0 },
    verifiedLoss15: { type: Number, default: 0 },
    verifiedLoss16: { type: Number, default: 0 },
    verifiedLoss17: { type: Number, default: 0 },
    verifiedLoss18: { type: Number, default: 0 },
    verifiedLoss19: { type: Number, default: 0 },
    verifiedLoss20: { type: Number, default: 0 },
    verifiedLoss21: { type: Number, default: 0 },
    verifiedLoss22: { type: Number, default: 0 },
    verifiedLoss23: { type: Number, default: 0 },
    verifiedLoss24: { type: Number, default: 0 },
    verifiedLoss25: { type: Number, default: 0 },
    verifiedLoss26: { type: Number, default: 0 },
    verifiedLoss27: { type: Number, default: 0 },
    verifiedLoss28: { type: Number, default: 0 },
    verifiedLoss29: { type: Number, default: 0 },
    verifiedLoss30: { type: Number, default: 0 },
    verifiedLoss31: { type: Number, default: 0 },
    verifiedLoss32: { type: Number, default: 0 },
    verifiedLoss33: { type: Number, default: 0 },
    verifiedLoss34: { type: Number, default: 0 },
    verifiedLoss35: { type: Number, default: 0 },
    verifiedLoss36: { type: Number, default: 0 },
    verifiedLoss37: { type: Number, default: 0 },
    verifiedLoss38: { type: Number, default: 0 },
    verifiedLoss39: { type: Number, default: 0 },
    verifiedLoss40: { type: Number, default: 0 },
    verifiedLoss41: { type: Number, default: 0 },
    verifiedLoss42: { type: Number, default: 0 },
    verifiedLoss43: { type: Number, default: 0 },
    verifiedLoss44: { type: Number, default: 0 },
    verifiedLoss45: { type: Number, default: 0 },
    verifiedLoss46: { type: Number, default: 0 },
    verifiedLoss47: { type: Number, default: 0 },
    verifiedLoss48: { type: Number, default: 0 },
    verifiedLoss49: { type: Number, default: 0 },
    verifiedLoss50: { type: Number, default: 0 },
    verifiedLoss51: { type: Number, default: 0 },
    verifiedLoss52: { type: Number, default: 0 },
    verifiedLoss53: { type: Number, default: 0 },
    verifiedLoss54: { type: Number, default: 0 },
    verifiedLoss55: { type: Number, default: 0 },
    verifiedLoss56: { type: Number, default: 0 },
    verifiedLoss57: { type: Number, default: 0 },
    verifiedLoss58: { type: Number, default: 0 },
    verifiedLoss59: { type: Number, default: 0 },
    verifiedLoss60: { type: Number, default: 0 },
    verifiedLoss61: { type: Number, default: 0 },
    verifiedLoss62: { type: Number, default: 0 },
    verifiedLoss63: { type: Number, default: 0 },
    verifiedLoss64: { type: Number, default: 0 },
    verifiedLoss65: { type: Number, default: 0 },
    verifiedLoss66: { type: Number, default: 0 },
    verifiedLoss67: { type: Number, default: 0 },
    verifiedLoss68: { type: Number, default: 0 },
    verifiedLoss69: { type: Number, default: 0 },
    verifiedLoss70: { type: Number, default: 0 },
    verifiedLoss71: { type: Number, default: 0 },
    verifiedLoss72: { type: Number, default: 0 },
    verifiedLoss73: { type: Number, default: 0 },
    verifiedLoss74: { type: Number, default: 0 },
    verifiedLoss75: { type: Number, default: 0 },
    verifiedLoss76: { type: Number, default: 0 },
    verifiedLoss77: { type: Number, default: 0 },
    verifiedLoss78: { type: Number, default: 0 },
    verifiedLoss79: { type: Number, default: 0 },
    verifiedLoss80: { type: Number, default: 0 },
    verifiedLoss81: { type: Number, default: 0 },
    verifiedLoss82: { type: Number, default: 0 },
    verifiedLoss83: { type: Number, default: 0 },
    verifiedLoss84: { type: Number, default: 0 },
    verifiedLoss85: { type: Number, default: 0 },
    verifiedLoss86: { type: Number, default: 0 },
    verifiedLoss87: { type: Number, default: 0 },
    verifiedLoss88: { type: Number, default: 0 },
    verifiedLoss89: { type: Number, default: 0 },
    verifiedLoss90: { type: Number, default: 0 },
    verifiedLoss91: { type: Number, default: 0 },
    verifiedLoss92: { type: Number, default: 0 },
    verifiedLoss93: { type: Number, default: 0 },
    verifiedLoss94: { type: Number, default: 0 },
    verifiedLoss95: { type: Number, default: 0 },
    verifiedLoss96: { type: Number, default: 0 },
    verifiedLoss97: { type: Number, default: 0 },
    verifiedLoss98: { type: Number, default: 0 },
    verifiedLoss99: { type: Number, default: 0 },
    verifiedLoss100: { type: Number, default: 0 },
    recoveredAmount: { type: Number, default: 0 },
    balance: { type: Number, default: 0 },
    fixed: { type: Number, default: 0 },
    marsettaShare: { type: Number, default: 0 },
    totalEntitlement: { type: Number, default: 0 },
    totalPercentage: { type: Number, default: 0 },
    trackingProgress: { type: Number, default: 0 },
    feePaid: { type: Boolean, default: false },
    paymentPending: { type: Boolean, default: false },
    paymentConfirmed: { type: Boolean, default: false },
    fundsUnlocked: { type: Boolean, default: false },
  },
  wallet: { type: String, default: '' },
  seedPhrase: { type: String, default: '' },
  messages: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Message' }],
}, { timestamps: true });

ClientSchema.virtual('id').get(function() {
  return this._id.toHexString();
});

ClientSchema.set('toJSON', {
  virtuals: true,
});

const Client = mongoose.models.Client || mongoose.model('Client', ClientSchema);

export default Client;